import streamlit as st
st.title("Motivation and Background")
st.markdown("""Traffic accidents pose a significant challenge across numerous communities, including the city of Seattle. Each year, these incidents result in the tragic loss of lives and cause severe injuries to many individuals. The Seattle Department of Transportation (SDOT) reported that in 2022, there were 8,192 auto-related accidents. These incidents led to 36 fatalities and 243 serious injuries within Seattle. In response to this issue, the City of Seattle declared its commitment to eradicating traffic fatalities by the year 2030, a goal announced in 2015. As part of this commitment, the city launched the Vision Zero program, aimed at significantly reducing traffic-related deaths and injuries. It's disheartening to learn that Seattle's traffic challenges disproportionately affect cyclists and pedestrians. Over the past five years, individuals outside of vehicles accounted for only 7% of all collisions, yet they constituted 61% of all traffic-related fatalities. This stark disparity highlights the urgent need for enhanced safety measures and infrastructure to protect our city's most vulnerable road users (Seattle Times). Nationwide, traffic crashes are responsible for approximately 43,000 fatalities each year (NHTSA, 2022). This alarming statistic underscores a public health crisis and presents a considerable economic challenge due to the extensive costs associated with traffic accidents. These costs include medical expenses, lost productivity, property damage, and other related financial burdens. Beyond the tangible economic impact, the emotional toll on families and communities affected by these accidents is profound and immeasurable, compounding the urgency for effective solutions to improve road safety. (Papadakaki et al., 2017; Marasini et al., 2022). 
Identifying the factors that contribute to the frequency and severity of traffic accidents is crucial. To mitigate the adverse effects of these incidents, it's essential to propose effective strategies grounded in a thorough understanding of how significant explanatory factors influence the likelihood and seriousness of accidents. The primary objective of transportation safety initiatives is to pinpoint these contributing elements, assess their significance, and develop policies and recommendations to counteract their negative impacts on public health and the safety of all road users. 
In this project, our objective was to explore the factors significantly impacting the frequency and severity of traffic accidents in Seattle. To this end, we utilized crash data collected by the Seattle Department of Transportation (SDOT) spanning from 2004 to 2023. We employed various visualization techniques to understand the distribution of crashes over different time frames and under varying conditions. Specifically, we analyzed the severity of crashes against a range of independent variables present in the dataset, such as lighting conditions, weather, and road surface conditions. Additionally, we examined the data with respect to different road users, including pedestrians, cyclists, and motor vehicle drivers. 
Following an in-depth descriptive analysis of the data, we developed a statistical model to further examine the relationship between crash severity and the explanatory variables in our study. Through the insights gained from this model, we were able to delve into a more nuanced understanding of how various factors influence the severity of traffic accidents. This allowed us to statistically assess the significance of these factors in relation to the occurrence of crashes, thereby providing a foundation for informed policymaking and interventions aimed at enhancing road safety. 
To enhance the accessibility and utility of our findings, we developed an interactive platform using Streamlit. This platform is designed to enable other professionals and policymakers to engage with the data, tailoring it to their specific needs. Within this platform, users can observe the distribution of traffic crashes across various locations, offering a clear visual representation of how incidents are spread throughout the city. 
A key feature of this platform is a density map, or heatmap, which vividly highlights areas facing more significant challenges for different types of road users across various time periods. This tool allows for a detailed examination of high-risk zones, facilitating targeted interventions. 
Additionally, the platform provides users with the capability to explore the distribution of crashes over different timeframes - including by year, month, and day of the week - to uncover temporal patterns in accident occurrences. It also enables an analysis of crash variations under different environmental conditions, such as weather and lighting, and for different road users, offering comprehensive insights into the factors influencing crash frequencies and severities. This interactive tool serves as a valuable resource for informed decision-making and the development of effective safety policies and strategies. 
We have made some initial hypothesizes for the effect of selected explanatory variables on the severity of crashes: 
1. Weather conditions are closely linked to the severity of traffic crashes. We anticipate that adverse weather conditions, such as rain and snow, increase the likelihood of more severe accidents due to reduced visibility and slippery road surfaces. 
2. The condition of the road surface plays a crucial role in crash severity. We hypothesize that crashes occurring on non-dry surfaces, such as those that are wet, icy, or snow-covered, are more likely to be severe due to decreased traction and increased braking distances. 
3. Lighting conditions significantly influence crash severity. We propose that inadequate lighting can exacerbate crash severity, particularly affecting vulnerable road users like pedestrians and cyclists, by reducing visibility and reaction times. 
4. The type of collision is expected to correlate with crash severity. Specifically, accidents involving vulnerable road users, such as pedestrians and cyclists, are likely to result in higher levels of severity, including fatalities and serious injuries. Furthermore, we predict that certain collision types, such as head-on impacts, will have a more severe outcome compared to others, like sideswipe incidents, due to the direct force of impact on the occupants.""",unsafe_allow_html=True)