import streamlit as st
st.title("Analysis and Interpretation")
st.markdown("""First, we investigate the temporal changes of the crash frequency from 2004 to 2023 for different levels of crash severity. The data illustrated in Figures 1-4 show the changes in crash frequency at different levels of severity. We can observe that: 
• The total number of crashes has decreased significantly from around 16000 in 2004 to about 7000 in 2023. It means that the reduction in the total number of accidents was more than 56%.  
• The percentage of injury crashes has remained fairly constant, while the percentage of serious injury crashes has increased from 1.5% to 3.5%. It may be concluded that the probability of more severe crashes has increased in recent years. 
• The percentage of fatal crashes has increased in recent years. This also implies that we have had more serious crashes in recent years, and the probability of more severe crashes has increased significantly. • About 62% of the crashes were property damage only (PDO) crashes. 
• Injury crashes’ share from the total crashes is about 26.6%. 
• The share of fatal crashes was about 0.2% and for the severe injury crashes it has been 1.4%. So, most severe crashes consisted of less than 2% of total crashes. 
• 10% of the crashes were labeled unknown in the dataset. • A considerable number of fatal crashes have occurred at intersections (about 42%). More than half of the serious injury crashes and injury crashes were also reported at intersections. So, we can conclude that intersections are a risky place and more probable for the occurrence of severe and fatal incidents.
            • The most common type of collisions has been Parked Car related collisions (25%). 
• Angle and Rear-ended collisions are also common types of collisions (18%). 
• Sideswipes and left turn are other common types of collisions (8-10%). 
• Pedestrian and Cyclists related crashes are also about 4-5% of the total crashes, which considering the low exposure rate of them, consists of a relatively high proportion of crashes
            • Regarding the cyclist related crashes, they contributed to 8% of total fatal crashes, 13% of injury and 9% of serious injury crashes. It can be concluded that most of these crashes resulted in severe outcomes. That makes sense because cyclists are vulnerable to the impact of collisions, and they are more probable to suffer from severe injuries as a result of a collision. 
• More than 5% of fatal crashes were head-on collisions. It can be observed that these crashes often lead to severe outcomes. The reason is that in head-on collisions, the vehicles kinematic energy is so high because of the movement in opposite directions and the cumulative effect of their speed on the final outcome. 
• In the case of parked car related collisions which were identified as the most common type of crash, most of the collisions resulted in property damage only. That’s also reasonable because the vehicle in the park is stationery and collisions mostly occur because of the driver’s inattention and mostly result in slight damage to the body of the vehicle. 
• Regarding the pedestrian related collisions, it can be observed that more than 40% of the total fatal crashes are related to this category. Also, more than 30% of serious injury crashes are in this category. It can be easily understood that the pedestrian involvement in a crash, results in severe outcomes and in most of the cases it is associated with fatalities and disabilities. The reason is the lack of protection for the pedestrians and their vulnerability to the impacts from collision. Serious strategies and policies should be taken to mitigate the involvement of pedestrians in traffic crashes. 
• In the case of rear-ended collisions, injury and property damage were only the most common outcomes. Serious injury or fatalities are not so common in this type of crash. The reason is that rear ended collisions often occur because of driver’s inattention, and it often results in damage to the vehicle’s body or slight injuries to the occupants. 
• Sideswipe collisions often resulted in property damage only. In some cases, it resulted in injury outcomes as well. The reason is that in sideswipe collisions the vehicles collide because of right of way violations, inattention, lane changing without caution, and they often are associated with damage to the vehicle’s body. Just in the case of high-speed driving it might result in injuries.
            • Fatal crashes are significantly associated with poor lighting conditions. More than 45% of fatal crashes have happened during darkness, and it illuminates the effect of poor lighting condition on increasing the severity of the crashes. 
• More than 35% of serious injury collisions have occurred during poor light conditions. It also denotes that the crashes during the nighttime are more probable to result in severe injuries because of driver’s visibility and fatigue.""",unsafe_allow_html=True)